### ISSUE TITLE
Why the xml report is missing the score?

### ISSUE THREAD

**Issue by arielman** [rasjani/pylint_junit#2]
When I ran the below command:
`python -m pylint --rcfile=.pylintrc --exit-zero ${MODULE} > ${WORKSPACE}/testreport/pylint.log`

It prints at the end:
`Your code has been rated at 9.79/10`

why it doesn't reflect using this plugin?
I ran the command:
`python -m pylint --output-format=pylint_junit.JUnitReporter --rcfile=.pylintrc --exit-zero ${MODULE} > ${WORKSPACE}/testreport/pylint.xml`

**Comment by rasjani** [comment]
First, partially the reason is/was that junit report format doesn't really have a "proper" field to store that information. 

Second, i have faint recollection that the "rating" value isn't exposed to output plugin (maybe) 

Any suggestions regarding this ?

**Comment by arielman** [comment]
can this be fixed? I think this is the most important information...

**Comment by rasjani** [comment]
Verified, pylint does not expose the score to the reporter.
