### ISSUE TITLE
Console output no longer is produced with version 2.15 of pylint.

### ISSUE THREAD

**Issue by krcb197** [rasjani/pylint_junit#3]
In the previous version of pylint 2.14.5 the following command would result JUnit XML being streamed to the stdout console

```bash
pylint --output-format=pylint_junit.JUnitReporter src\
```

Therefore some CI scripts used the technique of piping this to a file e.g
 ```bash
pylint --output-format=pylint_junit.JUnitReporter src\ > ci_result.junit 
```

However in the latest version of pylint 2.15, that behaviour no longer works, though it still works with the json output reporter that ships with pylint. Using the example, of the json output in the documentation [pylint outputs](https://pylint.pycqa.org/en/v2.15.0/user_guide/usage/output.html), I was able to work around the problem of getting the JUnit in a file:
 ```bash
pylint --output-format=pylint_junit.JUnitReporter:ci_result.junit src\
```
I have changed the CI script to the following so that you get a readable output in the log as well as a the JUnit for analysis.
 ```bash
pylint --output-format=text,pylint_junit.JUnitReporter:ci_result.junit src\
```

I have had a look through the change history for PyLint 2.15 and I can't find an obvious reason for the why this behaviour has changed. However, the structure of the json reporter looks slightly different to the JUnit one.

**Comment by edgBR** [comment]
I have just the same problem

**Comment by Pierre-Sassoulas** [comment]
The reason it's not working anymore was bisected to https://github.com/PyCQA/astroid/pull/1514, see https://github.com/PyCQA/pylint/issues/8368#issuecomment-1451861020.

**Comment by MarcSkovMadsen** [comment]
I was a user of pylint2junit. It has the same issue since 2.15.

**Comment by SvenStaehs** [comment]
Thanks for the workaround! I can't use 0.3.4 because of #8 so switching to 0.3.3 with your workaround is very helpful!
